spring.application.name=product-service

server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/product_db?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#AWS

access-key=Access key
secret-key=SecretKey
region=ap-south-1
bucket-name=shopify-bucket-28

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

#Eureka instance
eureka.instance.prefer-ip-address=true
