apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ecommerce
  labels:
    app: product-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
        - name: product-service
          image: 087670584144.dkr.ecr.ap-south-2.amazonaws.com/product-service:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8082

          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/product_db?createDatabaseIfNotExist=true&useSSL=false"

            - name: SPRING_DATASOURCE_USERNAME
              value: "root"

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: MYSQL_ROOT_PASSWORD

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"

            - name: REGION
              value: "ap-south-2"

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecommerce
  labels:
    app: product-service

spec:
  selector:
    app: product-service

  ports:
    - name: http
      port: 8082
      targetPort: 8082

  type: ClusterIP