name: Terraform Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:

      # 1. Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Check GitHub OIDC context
      - name: Check GitHub OIDC context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Event: $GITHUB_EVENT_NAME"

      # 4. Configure AWS credentials using GitHub OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::087670584144:role/GitHubActions-ECR-EKS-Role
          aws-region: ap-south-2

      # 5. Terraform Format Check
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 6. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 7. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 8. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # 9. Terraform Apply
      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve tfplan